#the compose file version
version: "3.8"

services:

  webserver:
    image: nginx:stable-alpine
    container_name: felsville_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes: 
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - php
      - mysql
    networks:
      - felsville

  mysql:
    image: mysql:8.0.21
    container_name: felsville_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "33061:3306"
    environment: 
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes: 
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/mysql-custom.cnf
    networks:
      - felsville

  phpmyadmin:
    image: phpmyadmin
    restart: always
    container_name: felsville_PMA
    depends_on:
      - mysql
    ports:
      - "8082:80"
    environment:
      - PMA_HOST=${DB_HOST}
    networks:
      - felsville

  php:
    build:
      context: .
      dockerfile: ./docker/php/php.dockerfile
    container_name: felsville_php
    volumes: 
      - .:/var/www/html
    ports: 
      - "9000:9000"
    networks:
      - felsville
       
  redis:
    image: redis
    restart: unless-stopped
    container_name: felsville_redis
    volumes:
      - ./docker/redis/data:/data
    networks:
      - felsville

  composer:
    image: composer:latest
    container_name: felsville_composer
    volumes: 
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on: 
      - php
    networks:
      - felsville    

  npm:
    image: node:14.9
    container_name: felsville_npm
    volumes: 
      - .:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']

  artisan:
    build: 
      context: .
      dockerfile: ./docker/php/php.dockerfile
    container_name: felsville_artisan
    volumes: 
      - .:/var/www/html
    depends_on: 
      - mysql
    working_dir: /var/www/html
    entrypoint: ['php','/var/www/html/artisan']
    networks:
      - felsville

networks:
  felsville: